@CQRS_Architecture_BookManagementSystem_API_.NET_8_HostAddress = http://localhost:5058

GET {{CQRS_Architecture_BookManagementSystem_API_.NET_8_HostAddress}}/weatherforecast/
Accept: application/json

###
